name: bbk_ocr_superapp
description: BBK AI OCR (Upload + Camera + OCR + Validations + MT103 + Staff mode)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.12.0
  camera: ^0.10.5+9
  file_picker: ^8.0.0+1
  path_provider: ^2.1.3
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
