name: Build Flutter APK

on:
  workflow_dispatch: {}   # run by button
  push:
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      # If android/ is missing, create it (safe to run)
      - name: Ensure Android platform exists
        run: flutter create . --platforms=android

      - name: Get packages
        run: flutter pub get

      # Build a debug APK (signed with debug keystore → installs easily)
      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BBK-OCR-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
