name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Ensure lib/main.dart
        run: |
          mkdir -p lib
          if [ -f app_main.dart ]; then mv -f app_main.dart lib/main.dart; fi

      - name: Create Flutter skeleton if missing (android)
        run: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi

      - name: Fetch packages
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: bbk-ocr-app
          path: build/app/outputs/flutter-apk/app-release.apk
